export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_CART_REQUEST = "PRODUCT_CART_REQUEST";
export const PRODUCT_CART_SUCCESS = "PRODUCT_CART_SUCCESS";
export const PRODUCT_CART_FAIL = "PRODUCT_CART_FAIL";
